### ISSUE TITLE
仓库引用许可请求

### ISSUE THREAD

**Issue by MaxwellJay256** [LittleYe233/hitsz-physics-ib-reports#1]
你好！
我是 [HITSZ OpenAuto](https://github.com/HITSZ-OpenAuto) 组织的仓库维护者，我们希望在 [HITSZ-OpenAuto/PHYS1002](https://github.com/HITSZ-OpenAuto/PHYS1002) 中引用您的仓库，帮助到更多同学。
详情可见 https://github.com/HITSZ-OpenAuto/PHYS1002/pull/18
现请求您的引用许可。感谢您的贡献！

**Comment by LittleYe233** [comment]
@MaxwellJay256 没有问题，欢迎引用。
